#!/bin/sh

icon="🐏"
case $BLOCK_BUTTON in
	1) notify-send "$icon Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	3) notify-send "$icon Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs." ;;
esac

free -h | sed -n '2{p;q}' | awk '{print "'$icon'", $3 " / " $2}'
